#ifndef SERVER_CONFIG_H
#define SERVER_CONFIG_H

#define SERVER_PORT 8080
#define MAX_CLIENTS 10
#define CONNECTION_TIMEOUT 30
#define MESSAGE_BUFFER_SIZE 1024
#define PING_INTERVAL 15
#define ENABLE_LOGGING 1

#define NOT_STARTED 1;
#define STARTED 0;


#endif
